# Active profile
spring:
  profiles:
    active: DEV
---

#DEV
server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/igiftu_test
    username: postgres
    password: 1488
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  data:
    rest:
      base-path: /api
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 336219914276334
            client-secret: 1c2865b72496735e753c47a7ac6758a1

