# Active profile
spring:
  profiles:
    active: DEV
---

#DEV
server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/igiftu_test
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  data:
    rest:
      base-path: /api

