
#Default
server:
  port: 8080

#Spring
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/igiftu_test
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#   https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    username: igiftuwishlist@gmail.com
    password: ${EMAIL_PASS}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  social:
    facebook:
      appId: 336219914276334
      appSecret: ${FACEBOOK_SECRET}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 60425418670-j34jkdku9jm34rnt2qe8q4toliiflb98.apps.googleusercontent.com
            client-secret: ${GOOGLE_SECRET}
          facebook:
            client-id: 336219914276334
            client-secret: ${FACEBOOK_SECRET}

#AWS
aws:
  cred:
    key: ${AWS_KEY}
    pass: ${AWS_PASS}

redirect:
  front: ${OAUTH_REDIRECT}
  backend: https://igiftudev-app.herokuapp.com/signUp

#Web
web:
  host: ${WEB_HOST}

